dist: xenial

language: python

sudo: True

cache:
  - pip

python:
 - "3.7"

install:
  pip install pipenv --upgrade
  pipenv sync --dev

addons:
  postgresql: "10"

before_script:
  - psql -c 'create database tweets2text;' -U postgres

env:
  global:
    - S3_BUCKET_NAME=test-tweets-to-text-downloads
    - TWITTER_CONSUMER_KEY=foo
    - TWITTER_CONSUMER_SECRET=bar
    - TWITTER_ACCESS_TOKEN=whiz
    - TWITTER_ACCESS_TOKEN_SECRET=bang

script:
  pipenv run coverage run manage.py test --settings "config.settings.test" tweets2text
  pipenv run coverage report -m

after_success:
  pipenv run coveralls

