language: python

sudo: false

cache:
  - pip

python:
 - "3.6"
 - "3.7-dev"

install: "make"

before_script:
  - wget http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz -O /tmp/dynamodb_local_latest.tar.gz
  - mkdir /tmp/dynamodb/
  - tar -xzf /tmp/dynamodb_local_latest.tar.gz -C /tmp/dynamodb/

env:
  global:
    - S3_BUCKET_NAME=test-tweets-to-text-downloads
    - TWITTER_CONSUMER_KEY=foo
    - TWITTER_CONSUMER_SECRET=bar
    - TWITTER_ACCESS_TOKEN=whiz
    - TWITTER_ACCESS_TOKEN_SECRET=bang

script:
  - make test

after_success:
 - coveralls
