language: python

sudo: false

cache:
  - pip

python:
 - "3.6"

install: "make"

before_script:
  - make localdynamodb

env:
  global:
    - S3_BUCKET_NAME=test-tweets-to-text-downloads
    - TWITTER_CONSUMER_KEY=foo
    - TWITTER_CONSUMER_SECRET=bar
    - TWITTER_ACCESS_TOKEN=whiz
    - TWITTER_ACCESS_TOKEN_SECRET=bang

script:
  - make test

after_success:
 - coveralls
