dist: xenial

language: python

sudo: True

cache:
  - pip

python:
 - "3.7"

install:
  pipenv install --dev

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database tweets2text;' -U postgres

env:
  global:
    - S3_BUCKET_NAME=test-tweets-to-text-downloads
    - TWITTER_CONSUMER_KEY=foo
    - TWITTER_CONSUMER_SECRET=bar
    - TWITTER_ACCESS_TOKEN=whiz
    - TWITTER_ACCESS_TOKEN_SECRET=bang

script:
  - make test

after_success:
 - coveralls
