dist: xenial
language: python
sudo: true
cache:
- pip
python:
- '3.7'
install:
- pip install pipenv --upgrade
- pipenv sync --dev
addons:
  postgresql: '10'
before_script:
- psql -c 'create database tweets2text;' -U postgres
env:
  global:
  - DJANGO_ENV = test
  - PIPENV_VERBOSITY=-1
  - secure: Hf6DDXUHxJJ7thGi7NPUIhlqf6OEnE4tjB1zYU1Hp/wejglzLBIeBKdSasRXy4p8BTfioY7lwKonJHBPFgQV94IRG8jRQoWZD16pTE8vMvQ9lx71R4pV9rtHtoAvZbFSYuhq61jd3gyL6zaL1kiHE+R8pzeM1YiP5NGGHVY/4d3oGpm8XLxF/lUZVdYqvf6IbYqkqeW7l4VKGl0vYTNHff0vkByfAD7mcN8CMj5lf3FwFY4Q96/MEIZzrLbFzL4woEbxVnlANMJnhzZKDKIKnq1clpBDGj/BSqJcwKU2I6XeK3IXK9nKOkMsT0U4ywdDTHRyVgwwFxtJTPf/KtedEjTjdKoZFwVjq3/xJJQ0qUkNjwo2FMUx3R4tNEJEinQABpDBdhrzJvuKkGze7WJvbQwUqpi1CzikUUxrHPxNJ/Rzii2Da1QCbQknAxGQFe5Wu8gY1+STmZDckEW+DHthDA52DRxVpkEYl76SDsGp6pXr76kwnYbMRg2MeebjxawZGE6u7ONDyLgTid9n4bBAOyjoj4o5WJyPZEZK9kVybum/JSmjpuUuVwElI31+qWI1U9iFNX8WovHYWtQuDtx/RvBOiJAahYijfaaOSu/R8TJAurMO4XeG6kobiYtGMihPqQIauBDKZY5FS+xI34XU/FiGNeZCCRt+4EubVOuJBxY=
  - secure: cEpKQURHKp3wsFwnRje62dnGR48vZkpIjFY4ZvZMCKsgBG7ufZSvrWdIHJs2PanTjcVTKkM1Ut7ZveUv1Y6bRjlp5xbLkXfT1IaRK921C/d2WtxamjKWpQhHLEOMB+a3PMKZsrcSlRX/4kYAbQbd99Y9KRi/rq8BntSPMd8J++qGWweA93YvfmS1PejHthRgk8S9Z00Y0n0J2Bkzkl/xl3fJcN/jF7OoYGrmHj2LVMkm6MmLmZMwHWrCdwu4hEBp0M68sleXkcuvTD6TktpViktuMfnpQYq52lwPumPU8EekJmA1fbYxGEXLLkNyG+8MNhBjlXnNPzl0fDQo9UKudkT3pWHL1mkQAiwgfzlHDFvYZ8Rhw7dZZVxKPL+RggSJSYetMtPFVtBTJx00qv7l08dC3QNGNsBJg+TOV56iBMMJKMNj1osNQHT4+hbH+nA9T4D84R74gIqmLzaOwsYlbmK+njflZku1w4w2n07xzr0CAPvmaj0JZ0gB7YkDdXO/D2JU3WwdwO/Pndj34NjnKsH6Bx7kENDj1KZ1vkqojwFnR0cCMLo8i/Jv9tRiufhTLq0illn5a361AZ8j8qTKmPdmlCGmyzTcIugtEgCLoyFT1JIdE4cNngM33d0QN5BOF8Gl5L6oWS+u8EG0h0ydPPshtMMIcXh/zZvDx8ybZn0=
script:
- make test
after_success:
- test $TRAVIS_BRANCH = “master” && zappa update prod
before_install:
- openssl aes-256-cbc -K $encrypted_2e58cba46dd8_key -iv $encrypted_2e58cba46dd8_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
