# Generated by Django 2.2.2 on 2019-06-12 20:01

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tweets2text.twitter_api
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(null=True)),
                ('processing_completed_at', models.DateTimeField(null=True)),
                ('json_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'Account Activity',
            },
        ),
        migrations.CreateModel(
            name='FollowHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TweetTextCompilation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('init_tweet_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('final_tweet_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('init_tweet_deleted', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('tweets', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, size=None)),
                ('text', models.TextField(blank=True)),
            ],
            bases=(tweets2text.twitter_api.TwitterMixin, models.Model),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_str', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('screen_name', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('json_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('last_follow_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=(tweets2text.twitter_api.TwitterMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id_str'], name='id_str_index'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_follow_at'], name='last_follow_at_index'),
        ),
        migrations.AddField(
            model_name='tweettextcompilation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compilations', to='tweets2text.User'),
        ),
        migrations.AddField(
            model_name='followhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_history', to='tweets2text.User'),
        ),
        migrations.AddIndex(
            model_name='accountactivity',
            index=models.Index(fields=['received_at'], name='received_at_index'),
        ),
        migrations.AddIndex(
            model_name='tweettextcompilation',
            index=models.Index(fields=['requested_at'], name='requested_at_index'),
        ),
        migrations.AddIndex(
            model_name='tweettextcompilation',
            index=models.Index(fields=['completed_at'], name='completed_at_index'),
        ),
    ]
