# Generated by Django 2.2.3 on 2019-07-11 03:20

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweets2text', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountactivity',
            options={'verbose_name': 'Account Activity', 'verbose_name_plural': 'Account Activity'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'TweetsToText User', 'verbose_name_plural': 'TweetsToText Users'},
        ),
        migrations.AddField(
            model_name='tweettextcompilation',
            name='thread_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountactivity',
            name='json_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(editable=False),
        ),
        migrations.AlterField(
            model_name='accountactivity',
            name='processing_completed_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='accountactivity',
            name='processing_started_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='accountactivity',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='followhistory',
            name='event_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(editable=False),
        ),
        migrations.AlterField(
            model_name='followhistory',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='follow_history', to='tweets2text.User'),
        ),
        migrations.AlterField(
            model_name='tweettextcompilation',
            name='completed_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tweettextcompilation',
            name='final_tweet_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tweettextcompilation',
            name='init_tweet_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='tweettextcompilation',
            name='init_tweet_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(editable=False),
        ),
        migrations.AlterField(
            model_name='tweettextcompilation',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='tweettextcompilation',
            name='text',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='tweettextcompilation',
            name='tweets',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, editable=False, size=None),
        ),
        migrations.AlterField(
            model_name='tweettextcompilation',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='compilations', to='tweets2text.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_str',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='json_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_follow_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='screen_name',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
